language: node_js
sudo: false
node_js:
  - "4.6"
  - "5.12"
  - "6.9"
  - "7.2"
script: "npm run-script test-travis"
after_script: "npm install codeclimate-test-reporter && cat ./coverage/lcov.info | codeclimate-test-reporter"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 28f96add6a18ec07789389050ef6593f2207e60f153766418d39b92cb4db1e47
env:
  - CXX=g++-4.8
